mkdir -p /mnt/sda1/downloads_linux/.cache/fire
#mkdir -p /mnt/sda1/downloads_linux/.cache/pale
mkdir -p /mnt/sda1/downloads_linux/.cache/qupz
#mkdir -p /mnt/sda1/downloads_linux/cache_slim
mkdir -p /mnt/sda1/downloads_linux/thunderbird
#mkdir -p /mnt/sda1/downloads_linux/.data/iridium
#mkdir -p /mnt/sda1/downloads_linux/.cache/irid
#mkdir -p /mnt/sda1/downloads_linux/.data/iron
#mkdir -p /mnt/sda1/downloads_linux/.cache/iron
#mkdir -p /mnt/sda1/downloads_linux/.data/viva
#mkdir -p /mnt/sda1/downloads_linux/.cache/viva
#mkdir -p /mnt/sda1/downloads_linux/.data/opera
#mkdir -p /mnt/sda1/downloads_linux/.cache/opera